services:
  app:
    build: .
    ports:
      - "9292:9292"
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    environment:
      RACK_ENV: development
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/rocking_sinatra
      REDIS_URL: redis://redis:6379

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rocking_sinatra
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
